name: OnPullRequest

on:
  pull_request: 
    branches:
      - 'dev'
      - 'main'
      - 'master'
    types:
      - closed

defaults:
  run:
    shell: bash

env:
  GITHUB_WORKFLOW_FOLDER: ./.github/workflows
  JEMPI_APP_PATH: ./JeMPI_Apps

jobs:
  prepare:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/workflows/actions/prepare
  lint-check:
    needs: [prepare]
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/workflows/actions/lint
  build-check:
    needs: [lint-check]
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/workflows/actions/build-check
  test:
    needs: [build-check]
    runs-on: ubuntu-22.04
    continue-on-error: true # TODO: Uncomment this out once tests are in a better state - ${{ github.ref != 'refs/heads/main' && github.ref != 'refs/heads/master' }}
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/workflows/actions/test
  smoke-test:
    needs: [test]
    runs-on: ubuntu-22.04
    continue-on-error: ${{ github.ref != 'refs/heads/main' && github.ref != 'refs/heads/master' }}
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/workflows/actions/smoke-test