on:
  pull_request:
    branches:
      - jembi-base
    paths:
      - "JeMPI_Apps/JeMPI_UI/**"
jobs:
  common-setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install Yarn Package Manager
        run: npm install -g yarn

      - name: Change Directory
        run: cd JeMPI_Apps/JeMPI_UI

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

  lint-and-format:
    name: Lint and Format
    needs: common-setup
    runs-on: ubuntu-latest
    steps:
      - name: Run Formatter/Linter
        run: yarn lint && yarn format

  build:
    name: Build
    needs: common-setup
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: yarn build
